# Configuration of the memcache servers
memcache:
    servers:
        - localhost:11211

# Configuration for the SQL database
database:
    # Database type, can either be 'mysql', 'postgresql', or 'sqlite'
    type: mysql
    # Server host
    host: 127.0.0.1
    # Server port
    port: 3306
    # Database name, or SQLite database file
    name: radiosite
    # Database user to login as
    user: wessie
    # Database password to use with the login
    password: hackme

# Scattered options for the audio media.
media:
    # Path to the directory with music files
    directory: /my/music/directory